### ISSUE TITLE
"Please see the Copperhead's Building Android Guide for instructions."

### ISSUE THREAD

**Issue by invapid** [copperhead-security/android#1]
README - invalid link

**Comment by dmix** [comment]
The project is not quite ready for public consumption yet. 

We're planning to release an alpha version very soon. When that happens we'll post build instructions and open up all of the repos to the public. At the moment we have a few repos still marked private, as they still need some work before we can publish them.

If you sign up at https://copperhead.co/android we'll notify you by email when the alpha launches.

**Comment by thestinger** [comment]
@invapid: https://copperhead.co/2015/08/21/alpha

I'll update the README here to point at that post for now. (later, I'm tired right now :P)
