### ISSUE TITLE
add a setting for controlling random MAC addresses

### ISSUE THREAD

**Issue by thestinger** [copperhead-security/android#20]
The kernel feature can have a sysctl switch exposed, and then it can be wrapped as a system property to expose it in Settings -> Privacy.

**Comment by polyzen** [comment]
This addition would be great considering MAC address whitelists

**Comment by thestinger** [comment]
A sysctl is now implemented along with a property wrapping it. Just need to expose it in the settings app.

**Comment by thestinger** [comment]
This is fully implemented and will be in the ROMs published tomorrow.

**Comment by polyzen** [comment]
Awesome :)
