### ISSUE TITLE
PaX exception for PagerDuty

### ISSUE THREAD

**Issue by andy11** [copperhead-security/android#23]
This seems to still occur on the 8/26 build.  Turning on PaX Soft Mode prevents the crash from happening.

Not urgent, just wanted to pass this on in case there's some other corner case not covered by the fix from #18...

Sorry about referencing tons of other issues with the stack trace in #22. Will avoid doing that in the future.

--------- beginning of crash
F/libc    (11173): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x15f in tid 11246 (Thread-39)
I/DEBUG   (  202): property debug.db.uid not set; NOT waiting for gdb.
I/DEBUG   (  202): HINT: adb shell setprop debug.db.uid 100000
I/DEBUG   (  202): HINT: adb forward tcp:5039 tcp:5039
I/ActivityManager(  796): Displayed com.pagerduty.android/.LoginActivity: +498ms (total +1s409ms)
I/Timeline(  796): Timeline: Activity_windows_visible id: ActivityRecord{2e8398e1 u0 com.pagerduty.android/.LoginActivity t169} time:1031753
I/DEBUG   (  202): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  202): Build fingerprint: 'google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys'
I/DEBUG   (  202): Revision: '11'
I/DEBUG   (  202): ABI: 'arm'
I/DEBUG   (  202): pid: 11173, tid: 11246, name: Thread-39  >>> com.pagerduty.android <<<
I/DEBUG   (  202): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x15f
I/DEBUG   (  202):     r0 00000000  r1 8cb655c0  r2 8f1a8cc0  r3 8cb62000
I/DEBUG   (  202):     r4 00000000  r5 8cb62000  r6 00000001  r7 009aec8e
I/DEBUG   (  202):     r8 8cb62878  r9 918a1234  sl 918a0cec  fp 00000001
I/DEBUG   (  202):     ip 00000000  sp 8e7f4758  lr 91324973  pc 913246c8  cpsr 80010030
I/DEBUG   (  202): 
I/DEBUG   (  202): backtrace:
I/DEBUG   (  202):     00 pc 011396c8  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     01 pc 0113996f  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     02 pc 01141937  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     03 pc 01141b11  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     04 pc 0124da15  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     05 pc 011b813f  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     06 pc 0130180f  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     07 pc 010d1bb1  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     08 pc 00c5eeab  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     09 pc 00b38305  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     10 pc 00b383fb  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     11 pc 00b3524f  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     12 pc 007ebffd  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     13 pc 00d51a79  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     14 pc 00d4e751  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     15 pc 00d5104b  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     16 pc 01389fff  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     17 pc 00fe07ed  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     18 pc 00fe065b  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     19 pc 0023f8a1  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     20 pc 0021f73b  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     21 pc 00220c77  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     22 pc 00221093  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     23 pc 0022127f  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     24 pc 0021fa01  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     25 pc 00226d89  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     26 pc 0021f2e9  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     27 pc 0023464d  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     28 pc 00231243  /system/lib/libwebviewchromium.so
I/DEBUG   (  202):     29 pc 00013acd  /system/lib/libc.so (__pthread_start(void*)+30)
I/DEBUG   (  202):     30 pc 000119ff  /system/lib/libc.so (__start_thread+6)

**Comment by thestinger** [comment]
> Sorry about referencing tons of other issues with the stack trace in #22.

No worries. FWIW, you can wrap code blocks with a `~~~` line above and below instead of editing the content.

**Comment by thestinger** [comment]
Strange, this seems to be automatically handled for me. The PackageParser code I wrote logs the expected message, and it gets the permission for dynamic code generation added:

~~~
D/PackageParser(  608): adding MPROTECT exception due to setJavaScriptEnabled call in com.pagerduty.android
~~~

Not sure what's going wrong.

**Comment by thestinger** [comment]
@andy11: I think I see the problem. I don't handle this in the code path deciding if *new* permissions can be granted for apps that are already installed. I'm guessing that you already had this app installed before the update. Can you try uninstalling and reinstalling it?

I'll have to figure out a way to work around this issue.

**Comment by thestinger** [comment]
On the other hand now that the code to deal with this is in place, the problem won't occur anymore (i.e. it will be detected at first install). So, assuming that's the issue, nothing really has to be fixed.

**Comment by andy11** [comment]
Ah, that did it! May not even be worth handling if 99.99% of your users will be starting fresh from builds where the update is already in place. I'll try re-installing any apps that I have issues with. Thanks!

**Comment by thestinger** [comment]
It might be worth working around because I'll add new heuristics like this in the future (for example, scanning for libraries with text relocations).

**Comment by thestinger** [comment]
Closing in favour of #24.
